// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SaasPOS.Infrastructure.Data;

#nullable disable

namespace SaasPOS.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717180830_AddTimezoneColumns")]
    partial class AddTimezoneColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SaasPOS.Domain.Entities.AtributoCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreAtributo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TipoDato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("AtributosCategoria");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComercioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ComercioId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComercioId")
                        .HasColumnType("integer");

                    b.Property<string>("Correo")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<bool>("EsConsumidorFinal")
                        .HasColumnType("boolean");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ComercioId", "Identificacion")
                        .IsUnique()
                        .HasDatabaseName("ix_clientes_comercio_identificacion");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.ColaCorreo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ComercioId")
                        .HasColumnType("integer");

                    b.Property<string>("CuerpoHtml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer");

                    b.Property<int>("MaxIntentos")
                        .HasColumnType("integer");

                    b.Property<string>("UltimoError")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ComercioId");

                    b.HasIndex("Estado")
                        .HasDatabaseName("idx_cola_correos_estado")
                        .HasFilter("\"Estado\" = 'Pendiente'");

                    b.ToTable("ColaCorreos");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Comercio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaveFirmaEncriptada")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RutaFirmaElectronica")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("UsaFacturacionSRI")
                        .HasColumnType("boolean");

                    b.Property<string>("ZonaHorariaDefecto")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("Ruc")
                        .IsUnique()
                        .HasDatabaseName("ix_comercios_ruc");

                    b.ToTable("Comercios");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.ConfiguracionComercio", b =>
                {
                    b.Property<int>("ComercioId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsBarEscolar")
                        .HasColumnType("boolean");

                    b.Property<bool>("ImpresionAutomaticaTicket")
                        .HasColumnType("boolean");

                    b.Property<bool>("MostrarBotonCliente")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermiteVentaEnNegativo")
                        .HasColumnType("boolean");

                    b.HasKey("ComercioId");

                    b.ToTable("ConfiguracionesComercio");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.ConfiguracionSucursal", b =>
                {
                    b.Property<int>("SucursalId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsBarEscolar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("ImpresionAutomaticaTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("MostrarBotonCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("PermitePrecioNegociado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("PermiteVentaEnNegativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("SucursalId");

                    b.ToTable("ConfiguracionesSucursal", (string)null);
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("PrecioRealCobrado")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetalleVentas");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.LogAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ComercioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegistroId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("ValoresAnteriores")
                        .HasColumnType("jsonb");

                    b.Property<string>("ValoresNuevos")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ComercioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogsAuditoria");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComercioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoNotificacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("ComercioId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("SucursalId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.PagoComercio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComercioId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaPago")
                        .HasColumnType("date");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RegistradoPor")
                        .HasColumnType("integer");

                    b.Property<int>("SuscripcionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComercioId");

                    b.HasIndex("RegistradoPor");

                    b.HasIndex("SuscripcionId");

                    b.ToTable("PagosComercio");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LimiteAtributos")
                        .HasColumnType("integer");

                    b.Property<int>("LimiteSucursales")
                        .HasColumnType("integer");

                    b.Property<int>("LimiteUsuarios")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.PrecioVolumen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadMinima")
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("PrecioEspecial")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("PreciosVolumen");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("ComercioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostoProduccion")
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("ManejaStock")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("PrecioLista")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PrecioMinimo")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("TipoArticulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UnidadMedida")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ValoresDinamicos")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ComercioId")
                        .HasDatabaseName("idx_productos_comercio");

                    b.HasIndex("ValoresDinamicos")
                        .HasDatabaseName("idx_productos_jsonb");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ValoresDinamicos"), "GIN");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.RecetaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadRequerida")
                        .HasColumnType("numeric(10,4)");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoFinalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("ProductoFinalId");

                    b.ToTable("RecetasProducto");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.SolicitudRecuperacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AprobadoPor")
                        .HasColumnType("integer");

                    b.Property<int>("ComercioId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AprobadoPor");

                    b.HasIndex("ComercioId")
                        .HasDatabaseName("idx_solicitudes_recuperacion_comercio");

                    b.HasIndex("Estado")
                        .HasDatabaseName("idx_solicitudes_recuperacion_estado")
                        .HasFilter("\"Estado\" = 'Pendiente'");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SolicitudesRecuperacion");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.StockSucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadFisica")
                        .HasColumnType("numeric(10,4)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,4)")
                        .HasDefaultValue(0m);

                    b.Property<int>("SucursalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.HasIndex("ProductoId", "SucursalId")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_sucursal_producto");

                    b.ToTable("StockSucursal");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComercioId")
                        .HasColumnType("integer");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SerieFacturacion")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ComercioId");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Suscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComercioId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsProporcional")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaProximoCorte")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaUltimoPago")
                        .HasColumnType("date");

                    b.Property<decimal>("MontoCuota")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComercioId");

                    b.HasIndex("Estado")
                        .HasDatabaseName("idx_suscripciones_estado");

                    b.HasIndex("FechaProximoCorte")
                        .HasDatabaseName("idx_suscripciones_corte");

                    b.HasIndex("PlanId");

                    b.ToTable("Suscripciones");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("ComercioId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("integer");

                    b.Property<string>("ZonaHoraria")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ComercioId")
                        .HasDatabaseName("idx_usuarios_comercio");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("SucursalId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("ComercioId")
                        .HasColumnType("integer");

                    b.Property<int>("CuotasMeses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("EstadoSRI")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Efectivo");

                    b.Property<string>("ReferenciaTransaccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SucursalId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ValorCuota")
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ComercioId")
                        .HasDatabaseName("idx_ventas_comercio");

                    b.HasIndex("SucursalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.AtributoCategoria", b =>
                {
                    b.HasOne("SaasPOS.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Atributos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("SaasPOS.Domain.Entities.Comercio", "Comercio")
                        .WithMany("Categorias")
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comercio");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("SaasPOS.Domain.Entities.Comercio", "Comercio")
                        .WithMany("Clientes")
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comercio");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.ColaCorreo", b =>
                {
                    b.HasOne("SaasPOS.Domain.Entities.Comercio", "Comercio")
                        .WithMany()
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Comercio");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Comercio", b =>
                {
                    b.HasOne("SaasPOS.Domain.Entities.Plan", "Plan")
                        .WithMany("Comercios")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.ConfiguracionComercio", b =>
                {
                    b.HasOne("SaasPOS.Domain.Entities.Comercio", "Comercio")
                        .WithOne("Configuracion")
                        .HasForeignKey("SaasPOS.Domain.Entities.ConfiguracionComercio", "ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comercio");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.ConfiguracionSucursal", b =>
                {
                    b.HasOne("SaasPOS.Domain.Entities.Sucursal", "Sucursal")
                        .WithOne("Configuracion")
                        .HasForeignKey("SaasPOS.Domain.Entities.ConfiguracionSucursal", "SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.DetalleVenta", b =>
                {
                    b.HasOne("SaasPOS.Domain.Entities.Producto", "Producto")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaasPOS.Domain.Entities.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.LogAuditoria", b =>
                {
                    b.HasOne("SaasPOS.Domain.Entities.Comercio", "Comercio")
                        .WithMany("LogsAuditoria")
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaasPOS.Domain.Entities.Usuario", "Usuario")
                        .WithMany("LogsAuditoria")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Comercio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("SaasPOS.Domain.Entities.Comercio", "Comercio")
                        .WithMany("Notificaciones")
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaasPOS.Domain.Entities.Producto", "Producto")
                        .WithMany("Notificaciones")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SaasPOS.Domain.Entities.Sucursal", "Sucursal")
                        .WithMany("Notificaciones")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Comercio");

                    b.Navigation("Producto");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.PagoComercio", b =>
                {
                    b.HasOne("SaasPOS.Domain.Entities.Comercio", "Comercio")
                        .WithMany("Pagos")
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaasPOS.Domain.Entities.Usuario", "UsuarioRegistrador")
                        .WithMany("PagosRegistrados")
                        .HasForeignKey("RegistradoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaasPOS.Domain.Entities.Suscripcion", "Suscripcion")
                        .WithMany("Pagos")
                        .HasForeignKey("SuscripcionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comercio");

                    b.Navigation("Suscripcion");

                    b.Navigation("UsuarioRegistrador");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.PrecioVolumen", b =>
                {
                    b.HasOne("SaasPOS.Domain.Entities.Producto", "Producto")
                        .WithMany("PreciosVolumen")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Producto", b =>
                {
                    b.HasOne("SaasPOS.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SaasPOS.Domain.Entities.Comercio", "Comercio")
                        .WithMany("Productos")
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Comercio");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.RecetaProducto", b =>
                {
                    b.HasOne("SaasPOS.Domain.Entities.Producto", "Ingrediente")
                        .WithMany("RecetasComoIngrediente")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaasPOS.Domain.Entities.Producto", "ProductoFinal")
                        .WithMany("RecetasComoFinal")
                        .HasForeignKey("ProductoFinalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("ProductoFinal");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.SolicitudRecuperacion", b =>
                {
                    b.HasOne("SaasPOS.Domain.Entities.Usuario", "Aprobador")
                        .WithMany()
                        .HasForeignKey("AprobadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SaasPOS.Domain.Entities.Comercio", "Comercio")
                        .WithMany()
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaasPOS.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aprobador");

                    b.Navigation("Comercio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.StockSucursal", b =>
                {
                    b.HasOne("SaasPOS.Domain.Entities.Producto", "Producto")
                        .WithMany("Stocks")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaasPOS.Domain.Entities.Sucursal", "Sucursal")
                        .WithMany("Stocks")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Sucursal", b =>
                {
                    b.HasOne("SaasPOS.Domain.Entities.Comercio", "Comercio")
                        .WithMany("Sucursales")
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comercio");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Suscripcion", b =>
                {
                    b.HasOne("SaasPOS.Domain.Entities.Comercio", "Comercio")
                        .WithMany("Suscripciones")
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaasPOS.Domain.Entities.Plan", "Plan")
                        .WithMany("Suscripciones")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comercio");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SaasPOS.Domain.Entities.Comercio", "Comercio")
                        .WithMany("Usuarios")
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaasPOS.Domain.Entities.Sucursal", "Sucursal")
                        .WithMany("Usuarios")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Comercio");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Venta", b =>
                {
                    b.HasOne("SaasPOS.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SaasPOS.Domain.Entities.Comercio", "Comercio")
                        .WithMany("Ventas")
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaasPOS.Domain.Entities.Sucursal", "Sucursal")
                        .WithMany("Ventas")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaasPOS.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Comercio");

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Atributos");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Comercio", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Clientes");

                    b.Navigation("Configuracion");

                    b.Navigation("LogsAuditoria");

                    b.Navigation("Notificaciones");

                    b.Navigation("Pagos");

                    b.Navigation("Productos");

                    b.Navigation("Sucursales");

                    b.Navigation("Suscripciones");

                    b.Navigation("Usuarios");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Plan", b =>
                {
                    b.Navigation("Comercios");

                    b.Navigation("Suscripciones");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Producto", b =>
                {
                    b.Navigation("DetalleVentas");

                    b.Navigation("Notificaciones");

                    b.Navigation("PreciosVolumen");

                    b.Navigation("RecetasComoFinal");

                    b.Navigation("RecetasComoIngrediente");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Sucursal", b =>
                {
                    b.Navigation("Configuracion");

                    b.Navigation("Notificaciones");

                    b.Navigation("Stocks");

                    b.Navigation("Usuarios");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Suscripcion", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("LogsAuditoria");

                    b.Navigation("PagosRegistrados");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("SaasPOS.Domain.Entities.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
