-- ============================================================================
-- Migración: AddConfiguracionesComprobante (20260805120000)
-- Ejecutar manualmente contra la base de datos PostgreSQL local
-- ============================================================================

BEGIN;

-- 1. Agregar campo MostrarVentasAlCajero a ConfiguracionesSucursal
ALTER TABLE "ConfiguracionesSucursal"
ADD COLUMN "MostrarVentasAlCajero" boolean NOT NULL DEFAULT false;

-- 2. Crear tabla ConfiguracionesComprobante
CREATE TABLE "ConfiguracionesComprobante" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ComercioId" integer NOT NULL,
    "TipoComprobante" character varying(50) NOT NULL,
    "Habilitado" boolean NOT NULL DEFAULT true,
    "FechaCreacion" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_ConfiguracionesComprobante" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ConfiguracionesComprobante_Comercios_ComercioId"
        FOREIGN KEY ("ComercioId") REFERENCES "Comercios" ("Id") ON DELETE CASCADE
);

-- 3. Índice único: un comercio no puede tener duplicados del mismo tipo
CREATE UNIQUE INDEX ix_configuraciones_comprobante_comercio_tipo
ON "ConfiguracionesComprobante" ("ComercioId", "TipoComprobante");

-- 4. Seed: Ticket Digital (habilitado) para todos los comercios existentes
INSERT INTO "ConfiguracionesComprobante" ("ComercioId", "TipoComprobante", "Habilitado", "FechaCreacion")
SELECT c."Id", 'Ticket Digital', TRUE, NOW()
FROM "Comercios" c;

-- 5. Seed: Ticket Impreso (deshabilitado) para todos los comercios existentes
INSERT INTO "ConfiguracionesComprobante" ("ComercioId", "TipoComprobante", "Habilitado", "FechaCreacion")
SELECT c."Id", 'Ticket Impreso', FALSE, NOW()
FROM "Comercios" c;

-- 6. Seed: Factura Electrónica (habilitada solo si UsaFacturacionSRI = true)
INSERT INTO "ConfiguracionesComprobante" ("ComercioId", "TipoComprobante", "Habilitado", "FechaCreacion")
SELECT c."Id", 'Factura Electrónica',
    CASE WHEN c."UsaFacturacionSRI" = TRUE THEN TRUE ELSE FALSE END,
    NOW()
FROM "Comercios" c;

-- 7. Actualizar valores legacy en Ventas: 'Ticket Interno' → 'Ticket Digital'
UPDATE "Ventas"
SET "TipoComprobante" = 'Ticket Digital'
WHERE "TipoComprobante" = 'Ticket Interno';

-- 8. Registrar la migración en la tabla de historial de EF Core
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260805120000_AddConfiguracionesComprobante', '9.0.0');

COMMIT;
