CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE TABLE "Planes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" character varying(100) NOT NULL,
        "Precio" numeric(10,2) NOT NULL,
        "LimiteUsuarios" integer NOT NULL,
        "LimiteAtributos" integer NOT NULL,
        CONSTRAINT "PK_Planes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE TABLE "Comercios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Ruc" character varying(20) NOT NULL,
        "RazonSocial" character varying(200) NOT NULL,
        "PlanId" integer NOT NULL,
        "UsaFacturacionSRI" boolean NOT NULL,
        "RutaFirmaElectronica" character varying(500),
        "ClaveFirmaEncriptada" character varying(500),
        "FechaRegistro" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Comercios" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Comercios_Planes_PlanId" FOREIGN KEY ("PlanId") REFERENCES "Planes" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE TABLE "Categorias" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ComercioId" integer NOT NULL,
        "Nombre" character varying(200) NOT NULL,
        CONSTRAINT "PK_Categorias" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Categorias_Comercios_ComercioId" FOREIGN KEY ("ComercioId") REFERENCES "Comercios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE TABLE "Clientes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ComercioId" integer NOT NULL,
        "Identificacion" character varying(20) NOT NULL,
        "Nombre" character varying(300) NOT NULL,
        "Correo" character varying(256),
        "Direccion" text,
        "Telefono" character varying(20),
        "EsConsumidorFinal" boolean NOT NULL,
        CONSTRAINT "PK_Clientes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Clientes_Comercios_ComercioId" FOREIGN KEY ("ComercioId") REFERENCES "Comercios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE TABLE "ColaCorreos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ComercioId" integer,
        "Destinatario" character varying(256) NOT NULL,
        "Asunto" character varying(500) NOT NULL,
        "CuerpoHtml" text NOT NULL,
        "Intentos" integer NOT NULL,
        "MaxIntentos" integer NOT NULL,
        "Estado" character varying(50) NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "FechaEnvio" timestamp with time zone,
        "UltimoError" text,
        CONSTRAINT "PK_ColaCorreos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ColaCorreos_Comercios_ComercioId" FOREIGN KEY ("ComercioId") REFERENCES "Comercios" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE TABLE "ConfiguracionesComercio" (
        "ComercioId" integer NOT NULL,
        "EsBarEscolar" boolean NOT NULL,
        "MostrarBotonCliente" boolean NOT NULL,
        "PermiteVentaEnNegativo" boolean NOT NULL,
        "ImpresionAutomaticaTicket" boolean NOT NULL,
        CONSTRAINT "PK_ConfiguracionesComercio" PRIMARY KEY ("ComercioId"),
        CONSTRAINT "FK_ConfiguracionesComercio_Comercios_ComercioId" FOREIGN KEY ("ComercioId") REFERENCES "Comercios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE TABLE "Sucursales" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ComercioId" integer NOT NULL,
        "Nombre" character varying(200) NOT NULL,
        "Direccion" text,
        "Telefono" character varying(20),
        "SerieFacturacion" character varying(10),
        CONSTRAINT "PK_Sucursales" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Sucursales_Comercios_ComercioId" FOREIGN KEY ("ComercioId") REFERENCES "Comercios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE TABLE "Suscripciones" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ComercioId" integer NOT NULL,
        "PlanId" integer NOT NULL,
        "FechaInicio" date NOT NULL,
        "FechaProximoCorte" date NOT NULL,
        "MontoCuota" numeric(10,2) NOT NULL,
        "EsProporcional" boolean NOT NULL,
        "Estado" character varying(50) NOT NULL,
        "FechaUltimoPago" date,
        CONSTRAINT "PK_Suscripciones" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Suscripciones_Comercios_ComercioId" FOREIGN KEY ("ComercioId") REFERENCES "Comercios" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Suscripciones_Planes_PlanId" FOREIGN KEY ("PlanId") REFERENCES "Planes" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE TABLE "AtributosCategoria" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CategoriaId" integer NOT NULL,
        "NombreAtributo" character varying(200) NOT NULL,
        "TipoDato" character varying(50) NOT NULL,
        CONSTRAINT "PK_AtributosCategoria" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AtributosCategoria_Categorias_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES "Categorias" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE TABLE "Productos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ComercioId" integer NOT NULL,
        "CategoriaId" integer,
        "Nombre" character varying(300) NOT NULL,
        "TipoArticulo" character varying(50) NOT NULL,
        "ValoresDinamicos" jsonb,
        "ManejaStock" boolean NOT NULL,
        "UnidadMedida" character varying(50),
        "CostoProduccion" numeric(10,2) NOT NULL,
        "PrecioLista" numeric(10,2) NOT NULL,
        "PrecioMinimo" numeric(10,2) NOT NULL,
        CONSTRAINT "PK_Productos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Productos_Categorias_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES "Categorias" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Productos_Comercios_ComercioId" FOREIGN KEY ("ComercioId") REFERENCES "Comercios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE TABLE "Usuarios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ComercioId" integer NOT NULL,
        "SucursalId" integer,
        "Nombre" character varying(200) NOT NULL,
        "Email" character varying(256) NOT NULL,
        "PasswordHash" character varying(500) NOT NULL,
        "Rol" character varying(50) NOT NULL,
        "Activo" boolean NOT NULL,
        CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Usuarios_Comercios_ComercioId" FOREIGN KEY ("ComercioId") REFERENCES "Comercios" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Usuarios_Sucursales_SucursalId" FOREIGN KEY ("SucursalId") REFERENCES "Sucursales" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE TABLE "Notificaciones" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ComercioId" integer NOT NULL,
        "SucursalId" integer,
        "ProductoId" integer,
        "Titulo" character varying(300) NOT NULL,
        "Mensaje" text NOT NULL,
        "Leida" boolean NOT NULL,
        "TipoNotificacion" character varying(100) NOT NULL,
        "FechaEmision" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Notificaciones" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Notificaciones_Comercios_ComercioId" FOREIGN KEY ("ComercioId") REFERENCES "Comercios" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Notificaciones_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Notificaciones_Sucursales_SucursalId" FOREIGN KEY ("SucursalId") REFERENCES "Sucursales" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE TABLE "PreciosVolumen" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProductoId" integer NOT NULL,
        "CantidadMinima" numeric(10,4) NOT NULL,
        "PrecioEspecial" numeric(10,2) NOT NULL,
        CONSTRAINT "PK_PreciosVolumen" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PreciosVolumen_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE TABLE "RecetasProducto" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProductoFinalId" integer NOT NULL,
        "IngredienteId" integer NOT NULL,
        "CantidadRequerida" numeric(10,4) NOT NULL,
        CONSTRAINT "PK_RecetasProducto" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RecetasProducto_Productos_IngredienteId" FOREIGN KEY ("IngredienteId") REFERENCES "Productos" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_RecetasProducto_Productos_ProductoFinalId" FOREIGN KEY ("ProductoFinalId") REFERENCES "Productos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE TABLE "StockSucursal" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProductoId" integer NOT NULL,
        "SucursalId" integer NOT NULL,
        "CantidadFisica" numeric(10,4) NOT NULL,
        CONSTRAINT "PK_StockSucursal" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StockSucursal_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_StockSucursal_Sucursales_SucursalId" FOREIGN KEY ("SucursalId") REFERENCES "Sucursales" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE TABLE "LogsAuditoria" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ComercioId" integer NOT NULL,
        "UsuarioId" integer,
        "Accion" character varying(200) NOT NULL,
        "FechaHora" timestamp with time zone NOT NULL,
        "TablaAfectada" character varying(100) NOT NULL,
        "RegistroId" character varying(100) NOT NULL,
        "ValoresAnteriores" jsonb,
        "ValoresNuevos" jsonb,
        CONSTRAINT "PK_LogsAuditoria" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LogsAuditoria_Comercios_ComercioId" FOREIGN KEY ("ComercioId") REFERENCES "Comercios" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_LogsAuditoria_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE TABLE "PagosComercio" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ComercioId" integer NOT NULL,
        "SuscripcionId" integer NOT NULL,
        "MontoPagado" numeric(10,2) NOT NULL,
        "FechaPago" date NOT NULL,
        "MetodoPago" character varying(100) NOT NULL,
        "Referencia" character varying(200),
        "RegistradoPor" integer NOT NULL,
        CONSTRAINT "PK_PagosComercio" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PagosComercio_Comercios_ComercioId" FOREIGN KEY ("ComercioId") REFERENCES "Comercios" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PagosComercio_Suscripciones_SuscripcionId" FOREIGN KEY ("SuscripcionId") REFERENCES "Suscripciones" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_PagosComercio_Usuarios_RegistradoPor" FOREIGN KEY ("RegistradoPor") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE TABLE "Ventas" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ComercioId" integer NOT NULL,
        "SucursalId" integer NOT NULL,
        "UsuarioId" integer NOT NULL,
        "ClienteId" integer,
        "Total" numeric(12,2) NOT NULL,
        "TipoComprobante" character varying(50) NOT NULL,
        "EstadoSRI" character varying(50),
        "FechaVenta" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Ventas" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Ventas_Clientes_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Clientes" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Ventas_Comercios_ComercioId" FOREIGN KEY ("ComercioId") REFERENCES "Comercios" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Ventas_Sucursales_SucursalId" FOREIGN KEY ("SucursalId") REFERENCES "Sucursales" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Ventas_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE TABLE "DetalleVentas" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "VentaId" integer NOT NULL,
        "ProductoId" integer NOT NULL,
        "Cantidad" numeric(10,4) NOT NULL,
        "PrecioRealCobrado" numeric(10,2) NOT NULL,
        CONSTRAINT "PK_DetalleVentas" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DetalleVentas_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_DetalleVentas_Ventas_VentaId" FOREIGN KEY ("VentaId") REFERENCES "Ventas" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_AtributosCategoria_CategoriaId" ON "AtributosCategoria" ("CategoriaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_Categorias_ComercioId" ON "Categorias" ("ComercioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_clientes_comercio_identificacion ON "Clientes" ("ComercioId", "Identificacion");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX idx_cola_correos_estado ON "ColaCorreos" ("Estado") WHERE "Estado" = 'Pendiente';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_ColaCorreos_ComercioId" ON "ColaCorreos" ("ComercioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_Comercios_PlanId" ON "Comercios" ("PlanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_comercios_ruc ON "Comercios" ("Ruc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_DetalleVentas_ProductoId" ON "DetalleVentas" ("ProductoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_DetalleVentas_VentaId" ON "DetalleVentas" ("VentaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_LogsAuditoria_ComercioId" ON "LogsAuditoria" ("ComercioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_LogsAuditoria_UsuarioId" ON "LogsAuditoria" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_Notificaciones_ComercioId" ON "Notificaciones" ("ComercioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_Notificaciones_ProductoId" ON "Notificaciones" ("ProductoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_Notificaciones_SucursalId" ON "Notificaciones" ("SucursalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_PagosComercio_ComercioId" ON "PagosComercio" ("ComercioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_PagosComercio_RegistradoPor" ON "PagosComercio" ("RegistradoPor");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_PagosComercio_SuscripcionId" ON "PagosComercio" ("SuscripcionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_PreciosVolumen_ProductoId" ON "PreciosVolumen" ("ProductoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX idx_productos_comercio ON "Productos" ("ComercioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX idx_productos_jsonb ON "Productos" USING GIN ("ValoresDinamicos");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_Productos_CategoriaId" ON "Productos" ("CategoriaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_RecetasProducto_IngredienteId" ON "RecetasProducto" ("IngredienteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_RecetasProducto_ProductoFinalId" ON "RecetasProducto" ("ProductoFinalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_stock_sucursal_producto ON "StockSucursal" ("ProductoId", "SucursalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_StockSucursal_SucursalId" ON "StockSucursal" ("SucursalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_Sucursales_ComercioId" ON "Sucursales" ("ComercioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX idx_suscripciones_corte ON "Suscripciones" ("FechaProximoCorte");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX idx_suscripciones_estado ON "Suscripciones" ("Estado");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_Suscripciones_ComercioId" ON "Suscripciones" ("ComercioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_Suscripciones_PlanId" ON "Suscripciones" ("PlanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX idx_usuarios_comercio ON "Usuarios" ("ComercioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_usuarios_email ON "Usuarios" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_Usuarios_SucursalId" ON "Usuarios" ("SucursalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX idx_ventas_comercio ON "Ventas" ("ComercioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_Ventas_ClienteId" ON "Ventas" ("ClienteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_Ventas_SucursalId" ON "Ventas" ("SucursalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    CREATE INDEX "IX_Ventas_UsuarioId" ON "Ventas" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620051231_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260620051231_InitialCreate', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260623121700_AddPaymentFields') THEN
    ALTER TABLE "Ventas" ADD "MetodoPago" character varying(50) NOT NULL DEFAULT 'Efectivo';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260623121700_AddPaymentFields') THEN
    ALTER TABLE "Ventas" ADD "CuotasMeses" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260623121700_AddPaymentFields') THEN
    ALTER TABLE "Ventas" ADD "ValorCuota" numeric(12,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260623121700_AddPaymentFields') THEN
    ALTER TABLE "Ventas" ADD "ReferenciaTransaccion" character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260623121700_AddPaymentFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260623121700_AddPaymentFields', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717180830_AddTimezoneColumns') THEN
    ALTER TABLE "Usuarios" ADD "ZonaHoraria" character varying(64);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717180830_AddTimezoneColumns') THEN
    ALTER TABLE "StockSucursal" ADD "StockMinimo" numeric(10,4) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717180830_AddTimezoneColumns') THEN
    ALTER TABLE "Planes" ADD "LimiteSucursales" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717180830_AddTimezoneColumns') THEN
    ALTER TABLE "Comercios" ADD "Estado" character varying(20) NOT NULL DEFAULT 'Activo';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717180830_AddTimezoneColumns') THEN
    ALTER TABLE "Comercios" ADD "ZonaHorariaDefecto" character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717180830_AddTimezoneColumns') THEN
    CREATE TABLE "ConfiguracionesSucursal" (
        "SucursalId" integer NOT NULL,
        "EsBarEscolar" boolean NOT NULL DEFAULT FALSE,
        "MostrarBotonCliente" boolean NOT NULL DEFAULT FALSE,
        "PermiteVentaEnNegativo" boolean NOT NULL DEFAULT FALSE,
        "ImpresionAutomaticaTicket" boolean NOT NULL DEFAULT TRUE,
        "PermitePrecioNegociado" boolean NOT NULL DEFAULT FALSE,
        CONSTRAINT "PK_ConfiguracionesSucursal" PRIMARY KEY ("SucursalId"),
        CONSTRAINT "FK_ConfiguracionesSucursal_Sucursales_SucursalId" FOREIGN KEY ("SucursalId") REFERENCES "Sucursales" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717180830_AddTimezoneColumns') THEN
    CREATE TABLE "SolicitudesRecuperacion" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "ComercioId" integer NOT NULL,
        "Estado" character varying(20) NOT NULL DEFAULT 'Pendiente',
        "AprobadoPor" integer,
        "FechaSolicitud" timestamp with time zone NOT NULL,
        "FechaResolucion" timestamp with time zone,
        CONSTRAINT "PK_SolicitudesRecuperacion" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SolicitudesRecuperacion_Comercios_ComercioId" FOREIGN KEY ("ComercioId") REFERENCES "Comercios" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_SolicitudesRecuperacion_Usuarios_AprobadoPor" FOREIGN KEY ("AprobadoPor") REFERENCES "Usuarios" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_SolicitudesRecuperacion_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717180830_AddTimezoneColumns') THEN
    CREATE INDEX idx_solicitudes_recuperacion_comercio ON "SolicitudesRecuperacion" ("ComercioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717180830_AddTimezoneColumns') THEN
    CREATE INDEX idx_solicitudes_recuperacion_estado ON "SolicitudesRecuperacion" ("Estado") WHERE "Estado" = 'Pendiente';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717180830_AddTimezoneColumns') THEN
    CREATE INDEX "IX_SolicitudesRecuperacion_AprobadoPor" ON "SolicitudesRecuperacion" ("AprobadoPor");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717180830_AddTimezoneColumns') THEN
    CREATE INDEX "IX_SolicitudesRecuperacion_UsuarioId" ON "SolicitudesRecuperacion" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717180830_AddTimezoneColumns') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260717180830_AddTimezoneColumns', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804204508_AddTrialFields') THEN
    ALTER TABLE "Suscripciones" ADD "DiasExtendidos" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804204508_AddTrialFields') THEN
    ALTER TABLE "Notificaciones" ADD "SuscripcionId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804204508_AddTrialFields') THEN
    CREATE INDEX idx_suscripciones_trial ON "Suscripciones" ("Estado", "FechaProximoCorte") WHERE "Estado" IN ('Trial', 'Trial_Expirado');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804204508_AddTrialFields') THEN
    CREATE INDEX idx_notificaciones_suscripcion_tipo ON "Notificaciones" ("SuscripcionId", "TipoNotificacion") WHERE "SuscripcionId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804204508_AddTrialFields') THEN
    ALTER TABLE "Notificaciones" ADD CONSTRAINT "FK_Notificaciones_Suscripciones_SuscripcionId" FOREIGN KEY ("SuscripcionId") REFERENCES "Suscripciones" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260804204508_AddTrialFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260804204508_AddTrialFields', '9.0.0');
    END IF;
END $EF$;
COMMIT;

